engines:
  checkstyle:
    enabled: true
    config: 'config/checkstyle/checkstyle.xml'
  pmd:
    enabled: true
    config: 'config/pmd-rulesets/pmd-rules.xml'
exclude_paths: [
    "config/",
    "folder_to_exclude/",
    "Library.java"
]
