import org.slf4j.Logger;
import org.slf4j.Logger;
import java.lang.Object;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'skailasam' at '8/14/15 4:15 PM' with Gradle 2.5
 *
 * @author skailasam, @date 8/14/15 4:15 PM
 */
public class Library {
    /** Single line java doc to check our checkstyle plugin **/
	public boolean someLibraryMethod() {
        return true;
    }
}
