import org.junit.Test;
import static org.junit.Assert.*;
import org.slf4j.Logger;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'skailasam' at '8/14/15 4:15 PM' with Gradle 2.5
 *
 * @author skailasam, @date 8/14/15 4:15 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
